server:
  port: 8100

spring:
  application:
    name: currency-conversion-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka