server:
  port: 8000

spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5 #NEW
        wait-duration: 3s
        enable-exponential-backoff: true
      default:
        limitForPerdiod: 2
        limitRefreshPeriod: 10s
#resilience4j.retry.instances.sample-api.maxRetryAttempts=5 #OLD

# CHANGE-KUBERNETES
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: -%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] #SB3